%YAML:1.0

#common parameters
imu: 1
num_of_cam: 2  # 1 or 2

imu_topic: "/neo/vi_sensor/imu"
image0_topic: "/neo/rect/first/image"
image1_topic: "/neo/rect/second/image"
output_path: "/home/yves/Documents/Data/"

cam0_calib: "neo_cam_0.yaml"
cam1_calib: "neo_cam_1.yaml"
image_width: 752
image_height: 480

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.

#cam0 to body
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
#   data: [0, 0, 1, 0.015,
#          -1, 0, 0, 0.055,
#          0, -1, 0, 0.0065,
#          0, 0, 0, 1]
   data: [0, -0.3419960, 0.9397014, 0.015,
          -1, 0, 0, 0.055,
          0, -0.9397014, -0.3419960, 0.0065,
          0, 0, 0, 1]

#	R: 	 0, -sin(pitch),  cos(pitch)
#		-1,	      0,           0
#		 0, -cos(pitch), -sin(pitch)

#cam1 to body
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
#   data: [0, 0, 1, 0.015,
#          -1, 0, 0, -0.055,
#          0, -1, 0, 0.0065,
#          0, 0, 0, 1]
   data: [0, -0.3419960, 0.9397014, 0.015,
          -1, 0, 0, -0.055,
          0, -0.9397014, -0.3419960, 0.0065,
          0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2
gyr_n: 0.02         # gyroscope measurement noise standard deviation.     #0.05
acc_w: 0.0002         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#visualization parameters
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
